#!/usr/bin/env python3
"""Schema gate for release-gate-local quick backend contract summary JSON."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

REQUIRED_KEYS = {
    "schema_version",
    "result",
    "exit_code",
    "test_count",
    "duration_seconds",
    "log_path",
}
ALLOWED_RESULTS = {"pass", "fail"}


def _load_summary(path: Path) -> dict[str, Any]:
    try:
        text = path.read_text(encoding="utf-8")
    except FileNotFoundError as exc:
        raise RuntimeError(f"summary file not found: {path}") from exc
    except OSError as exc:
        raise RuntimeError(f"unable to read summary file: {path}: {exc}") from exc

    try:
        payload = json.loads(text)
    except json.JSONDecodeError as exc:
        raise RuntimeError(f"summary file is not valid JSON: {path}") from exc

    if not isinstance(payload, dict):
        raise RuntimeError("summary payload root must be an object")
    return payload


def validate_summary_payload(
    payload: dict[str, Any],
    *,
    required_schema_version: str,
) -> None:
    missing = REQUIRED_KEYS.difference(payload.keys())
    if missing:
        missing_sorted = ", ".join(sorted(missing))
        raise RuntimeError(f"summary payload missing required keys: {missing_sorted}")

    schema_version = str(payload.get("schema_version") or "")
    if schema_version != required_schema_version:
        raise RuntimeError(
            "schema_version mismatch: "
            f"expected `{required_schema_version}` got `{schema_version or 'missing'}`"
        )

    result = str(payload.get("result") or "")
    if result not in ALLOWED_RESULTS:
        raise RuntimeError(f"result must be one of {sorted(ALLOWED_RESULTS)} (got `{result}`)")

    exit_code = payload.get("exit_code")
    if not isinstance(exit_code, int):
        raise RuntimeError("exit_code must be an integer")
    if result == "pass" and exit_code != 0:
        raise RuntimeError("exit_code must be 0 when result is `pass`")
    if result == "fail" and exit_code == 0:
        raise RuntimeError("exit_code must be non-zero when result is `fail`")

    test_count = payload.get("test_count")
    if test_count is not None and not isinstance(test_count, int):
        raise RuntimeError("test_count must be integer or null")
    if isinstance(test_count, int) and test_count <= 0:
        raise RuntimeError("test_count must be greater than 0 when present")

    duration_seconds = payload.get("duration_seconds")
    if not isinstance(duration_seconds, int):
        raise RuntimeError("duration_seconds must be an integer")
    if duration_seconds < 0:
        raise RuntimeError("duration_seconds must be >= 0")

    log_path = payload.get("log_path")
    if not isinstance(log_path, str) or not log_path.strip():
        raise RuntimeError("log_path must be a non-empty string")


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Validate quick backend contract summary payload generated by release-gate-local."
        )
    )
    parser.add_argument(
        "--summary-file",
        default="/tmp/release-gate-local-quick-backend-tests-summary.json",
        help="Path to quick backend summary JSON.",
    )
    parser.add_argument(
        "--required-schema-version",
        default="v1",
        help="Expected schema version for summary payload.",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = _build_parser()
    args = parser.parse_args(argv)
    summary_path = Path(args.summary_file)

    print("[quick-backend-summary-gate] checking summary")
    print(f"  summary_file: {summary_path}")
    print(f"  required_schema_version: {args.required_schema_version}")

    try:
        payload = _load_summary(summary_path)
        validate_summary_payload(
            payload,
            required_schema_version=args.required_schema_version,
        )
    except RuntimeError as exc:
        print("[quick-backend-summary-gate] result: fail")
        print(f"  detail: {exc}")
        return 1

    print("[quick-backend-summary-gate] result: pass")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
