import unittest
from pathlib import Path

BACKEND_ROOT = Path(__file__).resolve().parents[1]
SECURITY_GATE_SCRIPT_PATH = BACKEND_ROOT / "scripts" / "security-gate.sh"


class SecurityGateContractTests(unittest.TestCase):
    def test_security_gate_supports_fast_and_full_profiles(self) -> None:
        text = SECURITY_GATE_SCRIPT_PATH.read_text(encoding="utf-8")
        self.assertIn("SECURITY_GATE_PROFILE", text)
        self.assertIn('SECURITY_GATE_PROFILE="${SECURITY_GATE_PROFILE:-full}"', text)
        self.assertIn('SECURITY_GATE_STEP_TIMEOUT_SECONDS="${SECURITY_GATE_STEP_TIMEOUT_SECONDS:-240}"', text)
        self.assertIn('SECURITY_GATE_HEARTBEAT_SECONDS="${SECURITY_GATE_HEARTBEAT_SECONDS:-30}"', text)
        self.assertIn('SECURITY_GATE_PYTEST_TIMEOUT_SECONDS="${SECURITY_GATE_PYTEST_TIMEOUT_SECONDS:-1200}"', text)
        self.assertIn('SECURITY_GATE_API_INVENTORY_TIMEOUT_SECONDS="${SECURITY_GATE_API_INVENTORY_TIMEOUT_SECONDS:-300}"', text)
        self.assertIn('SECURITY_GATE_SUMMARY_PATH="${SECURITY_GATE_SUMMARY_PATH:-/tmp/security-gate-summary.ndjson}"', text)
        self.assertIn('SECURITY_GATE_RETRY_TIMEOUT_ONCE="${SECURITY_GATE_RETRY_TIMEOUT_ONCE:-1}"', text)
        self.assertIn("run_python_step()", text)
        self.assertIn("run_pytest_step()", text)
        self.assertIn("run_shared_contract_cluster()", text)
        self.assertIn("run_fast_pytest_contract_suite()", text)
        self.assertIn("append_step_summary()", text)
        self.assertIn("scripts/run_with_timeout.py", text)
        self.assertIn("scripts/pytest_guard.py", text)
        self.assertIn('if [[ "${SECURITY_GATE_PROFILE}" == "fast" ]]; then', text)
        self.assertIn("fast profile: running core policy checks", text)
        self.assertIn("import smoke: app.main", text)
        self.assertIn("SECURITY_GATE_SKIP_IMPORT_SMOKE", text)
        self.assertIn('run_python_step "import_smoke_app_main" -c "import app.main"', text)

    def test_security_gate_supports_api_inventory_auto_write(self) -> None:
        text = SECURITY_GATE_SCRIPT_PATH.read_text(encoding="utf-8")
        self.assertIn("API_INVENTORY_AUTO_WRITE", text)
        self.assertIn("export_api_inventory.py --write", text)
        self.assertIn("export_api_inventory.py --check", text)
        self.assertIn("--emit-timings", text)

    def test_security_gate_checks_read_and_mutating_matrix_exports(self) -> None:
        text = SECURITY_GATE_SCRIPT_PATH.read_text(encoding="utf-8")
        self.assertIn("export_endpoint_authorization_matrix.py --check-current", text)
        self.assertIn("export_read_authorization_matrix.py --check-current", text)
        self.assertIn("export_memory_timeline_query_baseline.py", text)
        self.assertIn("--fail-on-date-function", text)
        self.assertIn("--fail-on-full-scan", text)

    def test_security_gate_includes_quick_backend_contract_cluster(self) -> None:
        text = SECURITY_GATE_SCRIPT_PATH.read_text(encoding="utf-8")
        self.assertIn("check_owasp_api_top10_mapping_contract.py", text)
        self.assertIn("check_api_contract_snapshot.py", text)
        self.assertIn("check_frontend_api_transport_contract.py", text)
        self.assertIn("check_frontend_security_headers_contract.py", text)
        self.assertIn("check_frontend_polling_governance_contract.py", text)
        self.assertIn("check_frontend_test_coverage_floor.py", text)
        self.assertIn("check_env_secret_manifest_contract.py", text)
        self.assertIn("check_duplicate_suffix_files.py", text)
        self.assertIn("check_module_size_budget.py", text)
        self.assertIn("check_runtime_switch_contract.py", text)
        self.assertIn("check_idempotency_normalization_contract.py", text)
        self.assertIn("check_event_tracking_privacy_contract.py", text)
        self.assertIn("check_event_registry_contract.py", text)
        self.assertIn("check_core_loop_event_contract.py", text)
        self.assertIn("check_supply_chain_workflow_contract.py", text)
        self.assertIn("check_observability_live_contract.py", text)
        self.assertIn("check_feature_flag_governance_contract.py", text)
        self.assertIn("check_store_compliance_contract.py", text)
        self.assertIn("check_ai_eval_scenario_matrix_contract.py", text)
        self.assertIn("check_ai_eval_golden_set_contract.py", text)
        self.assertIn("check_billing_grace_account_hold_policy_contract.py", text)
        self.assertIn("check_pricing_experiment_policy_contract.py", text)
        self.assertIn("check_growth_kill_switch_coverage_contract.py", text)

    def test_security_gate_full_profile_uses_timeout_wrapped_python_steps(self) -> None:
        text = SECURITY_GATE_SCRIPT_PATH.read_text(encoding="utf-8")
        self.assertIn("run_python_step \"check_function_level_authorization\"", text)
        self.assertIn("run_python_step \"check_ai_eval_release_gate\"", text)
        self.assertIn("run_python_step \"validate_security_evidence_p0_drill\"", text)
        self.assertIn("run_python_step \"validate_security_evidence_chaos_drill\"", text)
        self.assertIn("validate_security_evidence.py \\", text)
        self.assertIn("--kind key-rotation-drill", text)
        self.assertIn("--kind billing-console-drift", text)
        self.assertIn("--kind data-restore-drill", text)
        self.assertIn("--kind backup-restore-drill", text)
        self.assertIn("--kind chaos-drill", text)
        self.assertIn("tests/test_billing_console_drift_audit.py", text)
        self.assertIn("tests/test_billing_console_drift_workflow_contract.py", text)
        self.assertIn("tests/test_key_rotation_drill_audit.py", text)
        self.assertIn("tests/test_data_restore_drill_audit.py", text)
        self.assertIn("tests/test_backup_restore_drill_audit.py", text)
        self.assertIn("tests/test_backup_restore_drill_workflow_contract.py", text)
        self.assertIn("tests/test_chaos_drill_audit.py", text)
        self.assertIn("tests/test_chaos_drill_workflow_contract.py", text)
        self.assertIn("tests/test_security_evidence_utils.py", text)
        self.assertIn("tests/test_store_compliance_contract_policy.py", text)
        self.assertIn("tests/test_billing_grace_account_hold_policy_contract.py", text)
        self.assertIn("tests/test_pricing_experiment_policy_contract.py", text)
        self.assertIn("tests/test_growth_kill_switch_coverage_contract.py", text)
        self.assertIn("tests/test_event_tracking_privacy_contract.py", text)
        self.assertIn("tests/test_event_registry_contract.py", text)
        self.assertIn("tests/test_core_loop_event_contract.py", text)
        self.assertIn("tests/test_supply_chain_workflow_contract.py", text)
        self.assertIn("tests/test_observability_live_contract_script.py", text)
        self.assertIn("tests/test_feature_flag_governance_contract.py", text)
        self.assertIn("tests/test_frontend_idempotency_helper_contract.py", text)
        self.assertIn("tests/test_frontend_timeline_loadmore_guard_contract.py", text)
        self.assertIn("tests/test_pricing_experiment_dry_run.py", text)
        self.assertIn("tests/test_pricing_experiment_runtime.py", text)
        self.assertIn("tests/test_pricing_experiment_guardrail_snapshot.py", text)
        self.assertIn("tests/test_pricing_experiment_guardrail_workflow_contract.py", text)
        self.assertIn("tests/test_core_loop_snapshot_workflow_contract.py", text)
        self.assertIn("tests/test_events_log_retention.py", text)
        self.assertIn("tests/test_events_log_retention_script.py", text)
        self.assertIn("tests/test_events_log_lifecycle_script.py", text)
        self.assertIn("tests/test_events_log_retention_workflow_contract.py", text)
        self.assertIn("tests/test_api_contract_snapshot_gate.py", text)
        self.assertIn("tests/test_abuse_economics_runtime.py", text)
        self.assertIn("tests/test_push_abuse_budget_policy.py", text)
        self.assertIn("tests/test_push_sli_runtime.py", text)
        self.assertIn("tests/test_ai_eval_scenario_matrix_contract_policy.py", text)
        self.assertIn("tests/test_ai_eval_golden_set_contract_policy.py", text)
        self.assertIn("tests/test_ai_eval_golden_set_snapshot_script.py", text)
        self.assertIn("tests/test_ai_eval_scenario_matrix_snapshot_script.py", text)
        self.assertIn("tests/test_ai_eval_drift_detector_script.py", text)
        self.assertIn("tests/test_field_level_encryption.py", text)
        self.assertIn("tests/test_onboarding_quest_api.py", text)
        self.assertIn("tests/test_first_delight_api.py", text)
        self.assertIn("tests/test_sync_nudges_api.py", text)
        self.assertIn("tests/test_notification_authorization_matrix.py", text)
        self.assertIn("tests/test_notification_api.py", text)
        self.assertIn("tests/test_notification_outbox.py", text)
        self.assertIn("tests/test_notification_outbox_migration.py", text)
        self.assertIn("tests/test_notification_outbox_dead_replay_audit_script.py", text)
        self.assertIn("tests/test_notification_outbox_health_snapshot_script.py", text)
        self.assertIn("tests/test_notification_outbox_self_heal_workflow_contract.py", text)
        self.assertIn("tests/test_oncall_runtime_snapshot_script.py", text)
        self.assertIn("tests/test_router_registration_contract.py", text)
        self.assertIn("tests/test_clean_evidence_noise_script_contract.py", text)
        self.assertIn("tests/test_users_router_structure.py", text)
        self.assertIn("tests/test_structured_logging_contract.py", text)
        self.assertIn("tests/test_ai_router_metrics.py", text)
        self.assertIn("tests/test_offline_idempotency_normalization.py", text)
        self.assertIn("tests/test_timeline_runtime_metrics.py", text)
        self.assertIn("tests/test_timeline_runtime_alert_gate_script.py", text)
        self.assertIn("tests/test_timeline_hot_path_indexes_migration.py", text)
        self.assertIn("tests/test_notification_multichannel_runtime.py", text)
        self.assertIn("tests/test_runtime_metrics_cardinality_guard.py", text)
        self.assertIn("tests/test_dynamic_content_pipeline.py", text)
        self.assertIn("tests/test_perf_baseline_script.py", text)
        self.assertIn("tests/test_rate_limit_scope_dimensions.py", text)
        self.assertIn("tests/security/test_bola_matrix.py", text)
        self.assertIn("tests/security/test_bola_subject_matrix.py", text)
        self.assertIn("tests/test_owasp_api_top10_mapping_contract_policy.py", text)
        self.assertIn("tests/test_release_gate_workflow_contract.py", text)
        self.assertIn("tests/test_idempotency_normalization_contract.py", text)
        self.assertIn("tests/test_env_secret_manifest_contract.py", text)
        self.assertIn("tests/test_duplicate_suffix_files_contract.py", text)
        self.assertIn("tests/test_dev_doctor_script_contract.py", text)
        self.assertIn("tests/test_module_size_budget_contract.py", text)
        self.assertIn("tests/test_generate_env_secret_manifest_script_contract.py", text)
        self.assertIn("tests/test_quick_backend_contract_summary_gate.py", text)
        self.assertIn("tests/test_frontend_e2e_summary_schema_gate_script.py", text)
        self.assertIn("tests/test_frontend_e2e_summary_contract.py", text)
        self.assertIn("tests/test_frontend_e2e_summary_script.py", text)
        self.assertIn("tests/test_frontend_api_transport_contract.py", text)
        self.assertIn("tests/test_frontend_security_headers_contract.py", text)
        self.assertIn("check_ai_eval_release_gate.py", text)
        self.assertIn("check_prompt_rollout_stop_loss.py", text)
        self.assertIn("tests/test_ai_eval_release_gate.py", text)
        self.assertIn("tests/test_hybrid_eval_report.py", text)
        self.assertIn("tests/test_prompt_rollout_stop_loss.py", text)
        self.assertIn("check_admin_least_privilege.py", text)
        self.assertIn("tests/test_admin_least_privilege.py", text)
        self.assertIn("check_billing_edge_policy_contract.py", text)
        self.assertIn("check_store_enforcement_hooks_contract.py", text)
        self.assertIn("tests/test_billing_edge_policy_contract.py", text)
        self.assertIn("tests/test_store_enforcement_hooks_contract.py", text)
        self.assertIn("tests/test_ai_router_degraded_chaos.py", text)
        self.assertIn("tests/test_events_ingest_guard_store.py", text)


if __name__ == "__main__":
    unittest.main()
