// AUTO-GENERATED FILE. DO NOT EDIT.
// Source: docs/security/api-inventory.json
// Generator: frontend/scripts/generate-api-contract-types.mjs

export type ApiContractMethod = 'DELETE' | 'GET' | 'PATCH' | 'POST' | 'PUT' | 'WEBSOCKET';
export type ApiContractAuthPolicy = 'authenticated' | 'custom' | 'public';
export type ApiContractDataSensitivity = 'account_sensitive' | 'billing_sensitive' | 'operational' | 'public' | 'relationship_sensitive';

export type ApiContractEntry = {
  method: ApiContractMethod;
  path: string;
  authPolicy: ApiContractAuthPolicy;
  dataSensitivity: ApiContractDataSensitivity;
};

export const API_CONTRACT_ENTRIES = [
  { method: 'GET', path: '/', authPolicy: 'public', dataSensitivity: 'operational' },
  { method: 'GET', path: '/api/admin/audit-events', authPolicy: 'authenticated', dataSensitivity: 'public' },
  { method: 'GET', path: '/api/admin/moderation/queue', authPolicy: 'authenticated', dataSensitivity: 'public' },
  { method: 'POST', path: '/api/admin/moderation/{report_id}/resolve', authPolicy: 'authenticated', dataSensitivity: 'public' },
  { method: 'GET', path: '/api/admin/users/{user_id}/status', authPolicy: 'authenticated', dataSensitivity: 'public' },
  { method: 'POST', path: '/api/admin/users/{user_id}/unbind', authPolicy: 'authenticated', dataSensitivity: 'public' },
  { method: 'GET', path: '/api/appreciations', authPolicy: 'authenticated', dataSensitivity: 'public' },
  { method: 'POST', path: '/api/appreciations', authPolicy: 'authenticated', dataSensitivity: 'public' },
  { method: 'POST', path: '/api/auth/logout', authPolicy: 'public', dataSensitivity: 'account_sensitive' },
  { method: 'POST', path: '/api/auth/refresh', authPolicy: 'public', dataSensitivity: 'account_sensitive' },
  { method: 'POST', path: '/api/auth/token', authPolicy: 'public', dataSensitivity: 'account_sensitive' },
  { method: 'GET', path: '/api/baseline', authPolicy: 'authenticated', dataSensitivity: 'public' },
  { method: 'POST', path: '/api/baseline', authPolicy: 'authenticated', dataSensitivity: 'public' },
  { method: 'POST', path: '/api/billing/create-checkout-session', authPolicy: 'authenticated', dataSensitivity: 'billing_sensitive' },
  { method: 'POST', path: '/api/billing/create-portal-session', authPolicy: 'authenticated', dataSensitivity: 'billing_sensitive' },
  { method: 'GET', path: '/api/billing/entitlements/me', authPolicy: 'authenticated', dataSensitivity: 'billing_sensitive' },
  { method: 'GET', path: '/api/billing/reconciliation', authPolicy: 'authenticated', dataSensitivity: 'billing_sensitive' },
  { method: 'POST', path: '/api/billing/state-change', authPolicy: 'authenticated', dataSensitivity: 'billing_sensitive' },
  { method: 'POST', path: '/api/billing/webhooks/appstore', authPolicy: 'public', dataSensitivity: 'billing_sensitive' },
  { method: 'POST', path: '/api/billing/webhooks/googleplay', authPolicy: 'public', dataSensitivity: 'billing_sensitive' },
  { method: 'POST', path: '/api/billing/webhooks/stripe', authPolicy: 'public', dataSensitivity: 'billing_sensitive' },
  { method: 'GET', path: '/api/blueprint/', authPolicy: 'authenticated', dataSensitivity: 'public' },
  { method: 'POST', path: '/api/blueprint/', authPolicy: 'authenticated', dataSensitivity: 'public' },
  { method: 'GET', path: '/api/blueprint/date-suggestions', authPolicy: 'authenticated', dataSensitivity: 'public' },
  { method: 'POST', path: '/api/card-decks/draw', authPolicy: 'authenticated', dataSensitivity: 'relationship_sensitive' },
  { method: 'GET', path: '/api/card-decks/history', authPolicy: 'authenticated', dataSensitivity: 'relationship_sensitive' },
  { method: 'GET', path: '/api/card-decks/history/summary', authPolicy: 'authenticated', dataSensitivity: 'relationship_sensitive' },
  { method: 'GET', path: '/api/card-decks/list', authPolicy: 'authenticated', dataSensitivity: 'relationship_sensitive' },
  { method: 'POST', path: '/api/card-decks/respond/{session_id}', authPolicy: 'authenticated', dataSensitivity: 'relationship_sensitive' },
  { method: 'GET', path: '/api/card-decks/stats', authPolicy: 'authenticated', dataSensitivity: 'relationship_sensitive' },
  { method: 'GET', path: '/api/card-decks/{deck_id}/draw', authPolicy: 'authenticated', dataSensitivity: 'relationship_sensitive' },
  { method: 'GET', path: '/api/cards/', authPolicy: 'authenticated', dataSensitivity: 'relationship_sensitive' },
  { method: 'GET', path: '/api/cards/backlog', authPolicy: 'authenticated', dataSensitivity: 'relationship_sensitive' },
  { method: 'GET', path: '/api/cards/daily-status', authPolicy: 'authenticated', dataSensitivity: 'relationship_sensitive' },
  { method: 'GET', path: '/api/cards/draw', authPolicy: 'authenticated', dataSensitivity: 'relationship_sensitive' },
  { method: 'POST', path: '/api/cards/respond', authPolicy: 'authenticated', dataSensitivity: 'relationship_sensitive' },
  { method: 'GET', path: '/api/cards/{card_id}/conversation', authPolicy: 'authenticated', dataSensitivity: 'relationship_sensitive' },
  { method: 'POST', path: '/api/cooldown/rewrite-message', authPolicy: 'authenticated', dataSensitivity: 'public' },
  { method: 'POST', path: '/api/cooldown/start', authPolicy: 'authenticated', dataSensitivity: 'public' },
  { method: 'GET', path: '/api/cooldown/status', authPolicy: 'authenticated', dataSensitivity: 'public' },
  { method: 'GET', path: '/api/couple-goal', authPolicy: 'authenticated', dataSensitivity: 'public' },
  { method: 'POST', path: '/api/couple-goal', authPolicy: 'authenticated', dataSensitivity: 'public' },
  { method: 'POST', path: '/api/daily-sync', authPolicy: 'authenticated', dataSensitivity: 'public' },
  { method: 'GET', path: '/api/daily-sync/status', authPolicy: 'authenticated', dataSensitivity: 'public' },
  { method: 'GET', path: '/api/journals', authPolicy: 'authenticated', dataSensitivity: 'relationship_sensitive' },
  { method: 'GET', path: '/api/journals/', authPolicy: 'authenticated', dataSensitivity: 'relationship_sensitive' },
  { method: 'POST', path: '/api/journals/', authPolicy: 'authenticated', dataSensitivity: 'relationship_sensitive' },
  { method: 'GET', path: '/api/journals/partner', authPolicy: 'authenticated', dataSensitivity: 'relationship_sensitive' },
  { method: 'DELETE', path: '/api/journals/{journal_id}', authPolicy: 'authenticated', dataSensitivity: 'relationship_sensitive' },
  { method: 'GET', path: '/api/journals/{journal_id}', authPolicy: 'authenticated', dataSensitivity: 'relationship_sensitive' },
  { method: 'PATCH', path: '/api/journals/{journal_id}', authPolicy: 'authenticated', dataSensitivity: 'relationship_sensitive' },
  { method: 'POST', path: '/api/journals/{journal_id}/attachments', authPolicy: 'authenticated', dataSensitivity: 'relationship_sensitive' },
  { method: 'DELETE', path: '/api/journals/{journal_id}/attachments/{attachment_id}', authPolicy: 'authenticated', dataSensitivity: 'relationship_sensitive' },
  { method: 'GET', path: '/api/love-languages/preference', authPolicy: 'authenticated', dataSensitivity: 'public' },
  { method: 'PUT', path: '/api/love-languages/preference', authPolicy: 'authenticated', dataSensitivity: 'public' },
  { method: 'GET', path: '/api/love-languages/weekly-task', authPolicy: 'authenticated', dataSensitivity: 'public' },
  { method: 'POST', path: '/api/love-languages/weekly-task/complete', authPolicy: 'authenticated', dataSensitivity: 'public' },
  { method: 'GET', path: '/api/love-map/cards', authPolicy: 'authenticated', dataSensitivity: 'public' },
  { method: 'GET', path: '/api/love-map/notes', authPolicy: 'authenticated', dataSensitivity: 'public' },
  { method: 'POST', path: '/api/love-map/notes', authPolicy: 'authenticated', dataSensitivity: 'public' },
  { method: 'PUT', path: '/api/love-map/notes/{note_id}', authPolicy: 'authenticated', dataSensitivity: 'public' },
  { method: 'GET', path: '/api/love-map/suggestions/shared-future', authPolicy: 'authenticated', dataSensitivity: 'public' },
  { method: 'POST', path: '/api/love-map/suggestions/shared-future/generate', authPolicy: 'authenticated', dataSensitivity: 'public' },
  { method: 'POST', path: '/api/love-map/suggestions/{suggestion_id}/accept', authPolicy: 'authenticated', dataSensitivity: 'public' },
  { method: 'POST', path: '/api/love-map/suggestions/{suggestion_id}/dismiss', authPolicy: 'authenticated', dataSensitivity: 'public' },
  { method: 'GET', path: '/api/love-map/system', authPolicy: 'authenticated', dataSensitivity: 'public' },
  { method: 'POST', path: '/api/mediation/answers', authPolicy: 'authenticated', dataSensitivity: 'public' },
  { method: 'POST', path: '/api/mediation/repair/start', authPolicy: 'authenticated', dataSensitivity: 'public' },
  { method: 'GET', path: '/api/mediation/repair/status', authPolicy: 'authenticated', dataSensitivity: 'public' },
  { method: 'POST', path: '/api/mediation/repair/step-complete', authPolicy: 'authenticated', dataSensitivity: 'public' },
  { method: 'GET', path: '/api/mediation/status', authPolicy: 'authenticated', dataSensitivity: 'public' },
  { method: 'GET', path: '/api/memory/calendar', authPolicy: 'authenticated', dataSensitivity: 'public' },
  { method: 'GET', path: '/api/memory/report', authPolicy: 'authenticated', dataSensitivity: 'public' },
  { method: 'GET', path: '/api/memory/time-capsule', authPolicy: 'authenticated', dataSensitivity: 'public' },
  { method: 'GET', path: '/api/memory/timeline', authPolicy: 'authenticated', dataSensitivity: 'public' },
  { method: 'POST', path: '/api/reports', authPolicy: 'authenticated', dataSensitivity: 'relationship_sensitive' },
  { method: 'GET', path: '/api/reports/weekly', authPolicy: 'authenticated', dataSensitivity: 'relationship_sensitive' },
  { method: 'POST', path: '/api/users/', authPolicy: 'public', dataSensitivity: 'account_sensitive' },
  { method: 'POST', path: '/api/users/events/core-loop', authPolicy: 'authenticated', dataSensitivity: 'account_sensitive' },
  { method: 'POST', path: '/api/users/events/cuj', authPolicy: 'authenticated', dataSensitivity: 'account_sensitive' },
  { method: 'GET', path: '/api/users/feature-flags', authPolicy: 'authenticated', dataSensitivity: 'account_sensitive' },
  { method: 'GET', path: '/api/users/first-delight', authPolicy: 'authenticated', dataSensitivity: 'account_sensitive' },
  { method: 'POST', path: '/api/users/first-delight/ack', authPolicy: 'authenticated', dataSensitivity: 'account_sensitive' },
  { method: 'GET', path: '/api/users/gamification-summary', authPolicy: 'authenticated', dataSensitivity: 'account_sensitive' },
  { method: 'POST', path: '/api/users/invite-code', authPolicy: 'authenticated', dataSensitivity: 'account_sensitive' },
  { method: 'GET', path: '/api/users/me', authPolicy: 'authenticated', dataSensitivity: 'account_sensitive' },
  { method: 'PATCH', path: '/api/users/me', authPolicy: 'authenticated', dataSensitivity: 'account_sensitive' },
  { method: 'GET', path: '/api/users/me/consents', authPolicy: 'authenticated', dataSensitivity: 'account_sensitive' },
  { method: 'POST', path: '/api/users/me/consents', authPolicy: 'authenticated', dataSensitivity: 'account_sensitive' },
  { method: 'DELETE', path: '/api/users/me/data', authPolicy: 'authenticated', dataSensitivity: 'relationship_sensitive' },
  { method: 'GET', path: '/api/users/me/data-export', authPolicy: 'authenticated', dataSensitivity: 'relationship_sensitive' },
  { method: 'GET', path: '/api/users/me/onboarding-consent', authPolicy: 'authenticated', dataSensitivity: 'account_sensitive' },
  { method: 'POST', path: '/api/users/me/onboarding-consent', authPolicy: 'authenticated', dataSensitivity: 'account_sensitive' },
  { method: 'GET', path: '/api/users/notifications', authPolicy: 'authenticated', dataSensitivity: 'account_sensitive' },
  { method: 'POST', path: '/api/users/notifications/mark-read', authPolicy: 'authenticated', dataSensitivity: 'account_sensitive' },
  { method: 'GET', path: '/api/users/notifications/stats', authPolicy: 'authenticated', dataSensitivity: 'account_sensitive' },
  { method: 'POST', path: '/api/users/notifications/{notification_id}/read', authPolicy: 'authenticated', dataSensitivity: 'account_sensitive' },
  { method: 'POST', path: '/api/users/notifications/{notification_id}/retry', authPolicy: 'authenticated', dataSensitivity: 'account_sensitive' },
  { method: 'GET', path: '/api/users/onboarding-quest', authPolicy: 'authenticated', dataSensitivity: 'account_sensitive' },
  { method: 'POST', path: '/api/users/pair', authPolicy: 'authenticated', dataSensitivity: 'account_sensitive' },
  { method: 'GET', path: '/api/users/partner-status', authPolicy: 'authenticated', dataSensitivity: 'account_sensitive' },
  { method: 'GET', path: '/api/users/push-subscriptions', authPolicy: 'authenticated', dataSensitivity: 'account_sensitive' },
  { method: 'POST', path: '/api/users/push-subscriptions', authPolicy: 'authenticated', dataSensitivity: 'account_sensitive' },
  { method: 'POST', path: '/api/users/push-subscriptions/dry-run', authPolicy: 'authenticated', dataSensitivity: 'account_sensitive' },
  { method: 'DELETE', path: '/api/users/push-subscriptions/{subscription_id}', authPolicy: 'authenticated', dataSensitivity: 'account_sensitive' },
  { method: 'GET', path: '/api/users/reengagement-hooks', authPolicy: 'authenticated', dataSensitivity: 'account_sensitive' },
  { method: 'POST', path: '/api/users/referrals/couple-invite', authPolicy: 'authenticated', dataSensitivity: 'account_sensitive' },
  { method: 'POST', path: '/api/users/referrals/landing-view', authPolicy: 'public', dataSensitivity: 'account_sensitive' },
  { method: 'POST', path: '/api/users/referrals/signup', authPolicy: 'authenticated', dataSensitivity: 'account_sensitive' },
  { method: 'GET', path: '/api/users/sync-nudges', authPolicy: 'authenticated', dataSensitivity: 'account_sensitive' },
  { method: 'POST', path: '/api/users/sync-nudges/{nudge_type}/deliver', authPolicy: 'authenticated', dataSensitivity: 'account_sensitive' },
  { method: 'GET', path: '/api/users/{user_id}', authPolicy: 'authenticated', dataSensitivity: 'account_sensitive' },
  { method: 'GET', path: '/health', authPolicy: 'public', dataSensitivity: 'operational' },
  { method: 'GET', path: '/health/deep', authPolicy: 'public', dataSensitivity: 'operational' },
  { method: 'GET', path: '/health/degradation', authPolicy: 'public', dataSensitivity: 'operational' },
  { method: 'GET', path: '/health/live', authPolicy: 'public', dataSensitivity: 'operational' },
  { method: 'GET', path: '/health/ready', authPolicy: 'public', dataSensitivity: 'operational' },
  { method: 'GET', path: '/health/slo', authPolicy: 'public', dataSensitivity: 'operational' },
  { method: 'GET', path: '/metrics', authPolicy: 'public', dataSensitivity: 'public' },
  { method: 'WEBSOCKET', path: '/ws/{user_id}', authPolicy: 'custom', dataSensitivity: 'relationship_sensitive' },
] as const;

export const MUTATING_API_PATHS = [
  '/api/admin/moderation/{report_id}/resolve',
  '/api/admin/users/{user_id}/unbind',
  '/api/appreciations',
  '/api/auth/logout',
  '/api/auth/refresh',
  '/api/auth/token',
  '/api/baseline',
  '/api/billing/create-checkout-session',
  '/api/billing/create-portal-session',
  '/api/billing/state-change',
  '/api/billing/webhooks/appstore',
  '/api/billing/webhooks/googleplay',
  '/api/billing/webhooks/stripe',
  '/api/blueprint/',
  '/api/card-decks/draw',
  '/api/card-decks/respond/{session_id}',
  '/api/cards/respond',
  '/api/cooldown/rewrite-message',
  '/api/cooldown/start',
  '/api/couple-goal',
  '/api/daily-sync',
  '/api/journals/',
  '/api/journals/{journal_id}',
  '/api/journals/{journal_id}/attachments',
  '/api/journals/{journal_id}/attachments/{attachment_id}',
  '/api/love-languages/preference',
  '/api/love-languages/weekly-task/complete',
  '/api/love-map/notes',
  '/api/love-map/notes/{note_id}',
  '/api/love-map/suggestions/{suggestion_id}/accept',
  '/api/love-map/suggestions/{suggestion_id}/dismiss',
  '/api/love-map/suggestions/shared-future/generate',
  '/api/mediation/answers',
  '/api/mediation/repair/start',
  '/api/mediation/repair/step-complete',
  '/api/reports',
  '/api/users/',
  '/api/users/events/core-loop',
  '/api/users/events/cuj',
  '/api/users/first-delight/ack',
  '/api/users/invite-code',
  '/api/users/me',
  '/api/users/me/consents',
  '/api/users/me/data',
  '/api/users/me/onboarding-consent',
  '/api/users/notifications/{notification_id}/read',
  '/api/users/notifications/{notification_id}/retry',
  '/api/users/notifications/mark-read',
  '/api/users/pair',
  '/api/users/push-subscriptions',
  '/api/users/push-subscriptions/{subscription_id}',
  '/api/users/push-subscriptions/dry-run',
  '/api/users/referrals/couple-invite',
  '/api/users/referrals/landing-view',
  '/api/users/referrals/signup',
  '/api/users/sync-nudges/{nudge_type}/deliver',
] as const;
export const API_PATHS = [
  '/api/admin/audit-events',
  '/api/admin/moderation/{report_id}/resolve',
  '/api/admin/moderation/queue',
  '/api/admin/users/{user_id}/status',
  '/api/admin/users/{user_id}/unbind',
  '/api/appreciations',
  '/api/auth/logout',
  '/api/auth/refresh',
  '/api/auth/token',
  '/api/baseline',
  '/api/billing/create-checkout-session',
  '/api/billing/create-portal-session',
  '/api/billing/entitlements/me',
  '/api/billing/reconciliation',
  '/api/billing/state-change',
  '/api/billing/webhooks/appstore',
  '/api/billing/webhooks/googleplay',
  '/api/billing/webhooks/stripe',
  '/api/blueprint/',
  '/api/blueprint/date-suggestions',
  '/api/card-decks/{deck_id}/draw',
  '/api/card-decks/draw',
  '/api/card-decks/history',
  '/api/card-decks/history/summary',
  '/api/card-decks/list',
  '/api/card-decks/respond/{session_id}',
  '/api/card-decks/stats',
  '/api/cards/',
  '/api/cards/{card_id}/conversation',
  '/api/cards/backlog',
  '/api/cards/daily-status',
  '/api/cards/draw',
  '/api/cards/respond',
  '/api/cooldown/rewrite-message',
  '/api/cooldown/start',
  '/api/cooldown/status',
  '/api/couple-goal',
  '/api/daily-sync',
  '/api/daily-sync/status',
  '/api/journals',
  '/api/journals/',
  '/api/journals/{journal_id}',
  '/api/journals/{journal_id}/attachments',
  '/api/journals/{journal_id}/attachments/{attachment_id}',
  '/api/journals/partner',
  '/api/love-languages/preference',
  '/api/love-languages/weekly-task',
  '/api/love-languages/weekly-task/complete',
  '/api/love-map/cards',
  '/api/love-map/notes',
  '/api/love-map/notes/{note_id}',
  '/api/love-map/suggestions/{suggestion_id}/accept',
  '/api/love-map/suggestions/{suggestion_id}/dismiss',
  '/api/love-map/suggestions/shared-future',
  '/api/love-map/suggestions/shared-future/generate',
  '/api/love-map/system',
  '/api/mediation/answers',
  '/api/mediation/repair/start',
  '/api/mediation/repair/status',
  '/api/mediation/repair/step-complete',
  '/api/mediation/status',
  '/api/memory/calendar',
  '/api/memory/report',
  '/api/memory/time-capsule',
  '/api/memory/timeline',
  '/api/reports',
  '/api/reports/weekly',
  '/api/users/',
  '/api/users/{user_id}',
  '/api/users/events/core-loop',
  '/api/users/events/cuj',
  '/api/users/feature-flags',
  '/api/users/first-delight',
  '/api/users/first-delight/ack',
  '/api/users/gamification-summary',
  '/api/users/invite-code',
  '/api/users/me',
  '/api/users/me/consents',
  '/api/users/me/data',
  '/api/users/me/data-export',
  '/api/users/me/onboarding-consent',
  '/api/users/notifications',
  '/api/users/notifications/{notification_id}/read',
  '/api/users/notifications/{notification_id}/retry',
  '/api/users/notifications/mark-read',
  '/api/users/notifications/stats',
  '/api/users/onboarding-quest',
  '/api/users/pair',
  '/api/users/partner-status',
  '/api/users/push-subscriptions',
  '/api/users/push-subscriptions/{subscription_id}',
  '/api/users/push-subscriptions/dry-run',
  '/api/users/reengagement-hooks',
  '/api/users/referrals/couple-invite',
  '/api/users/referrals/landing-view',
  '/api/users/referrals/signup',
  '/api/users/sync-nudges',
  '/api/users/sync-nudges/{nudge_type}/deliver',
] as const;
