"""Add CardDeck and deck_id

Revision ID: 37e3b353ac83
Revises: c4e2836dd74f
Create Date: 2026-02-12 09:07:41.961799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '37e3b353ac83'
down_revision: Union[str, Sequence[str], None] = 'c4e2836dd74f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carddeck',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_analyses_journal_id'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_user_id'), table_name='analyses')
    op.drop_table('analyses')
    op.drop_constraint(op.f('card_responses_session_id_fkey'), 'card_responses', type_='foreignkey')
    op.create_foreign_key(None, 'card_responses', 'card_sessions', ['session_id'], ['id'])
    op.alter_column('card_sessions', 'card_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('card_sessions', 'category',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('card_sessions', 'status',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               nullable=False,
               existing_server_default=sa.text("'PENDING'::text"))
    op.alter_column('card_sessions', 'creator_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('card_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('card_sessions_partner_id_fkey'), 'card_sessions', type_='foreignkey')
    op.drop_constraint(op.f('card_sessions_creator_id_fkey'), 'card_sessions', type_='foreignkey')
    op.drop_constraint(op.f('card_sessions_card_id_fkey'), 'card_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'card_sessions', 'users', ['partner_id'], ['id'])
    op.create_foreign_key(None, 'card_sessions', 'users', ['creator_id'], ['id'])
    op.create_foreign_key(None, 'card_sessions', 'cards', ['card_id'], ['id'])
    op.add_column('cards', sa.Column('deck_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cards', 'carddeck', ['deck_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cards', type_='foreignkey')
    op.drop_column('cards', 'deck_id')
    op.drop_constraint(None, 'card_sessions', type_='foreignkey')
    op.drop_constraint(None, 'card_sessions', type_='foreignkey')
    op.drop_constraint(None, 'card_sessions', type_='foreignkey')
    op.create_foreign_key(op.f('card_sessions_card_id_fkey'), 'card_sessions', 'cards', ['card_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('card_sessions_creator_id_fkey'), 'card_sessions', 'users', ['creator_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('card_sessions_partner_id_fkey'), 'card_sessions', 'users', ['partner_id'], ['id'], ondelete='CASCADE')
    op.alter_column('card_sessions', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('card_sessions', 'creator_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('card_sessions', 'status',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'PENDING'::text"))
    op.alter_column('card_sessions', 'category',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('card_sessions', 'card_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'card_responses', type_='foreignkey')
    op.create_foreign_key(op.f('card_responses_session_id_fkey'), 'card_responses', 'card_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.create_table('analyses',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('journal_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('mood_label', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('emotional_needs', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('advice_for_user', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('action_for_user', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('advice_for_partner', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('action_for_partner', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('card_recommendation', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('safety_tier', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('prompt_version', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['journal_id'], ['journals.id'], name=op.f('analyses_journal_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('analyses_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('analyses_pkey'))
    )
    op.create_index(op.f('ix_analyses_user_id'), 'analyses', ['user_id'], unique=False)
    op.create_index(op.f('ix_analyses_journal_id'), 'analyses', ['journal_id'], unique=False)
    op.drop_table('carddeck')
    # ### end Alembic commands ###
