"""init db with users and journals

Revision ID: 4106a6e78900
Revises: 
Create Date: 2026-02-06 18:09:00.899562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4106a6e78900'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journal', sa.Column('mood_label', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('journal', sa.Column('emotional_needs', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('journal', sa.Column('advice_for_user', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('journal', sa.Column('action_for_partner', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('journal', sa.Column('card_recommendation', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('journal', sa.Column('safety_tier', sa.Integer(), nullable=False))
    op.add_column('journal', sa.Column('prompt_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('journal', sa.Column('model_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('journal', sa.Column('parse_success', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_journal_user_id'), 'journal', ['user_id'], unique=False)
    op.drop_constraint(op.f('journal_user_id_fkey'), 'journal', type_='foreignkey')
    op.drop_column('journal', 'mood')
    op.drop_column('journal', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journal', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('journal', sa.Column('mood', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('journal_user_id_fkey'), 'journal', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_journal_user_id'), table_name='journal')
    op.drop_column('journal', 'parse_success')
    op.drop_column('journal', 'model_version')
    op.drop_column('journal', 'prompt_version')
    op.drop_column('journal', 'safety_tier')
    op.drop_column('journal', 'card_recommendation')
    op.drop_column('journal', 'action_for_partner')
    op.drop_column('journal', 'advice_for_user')
    op.drop_column('journal', 'emotional_needs')
    op.drop_column('journal', 'mood_label')
    # ### end Alembic commands ###
