"""add_response_status_to_sqlmodel

Revision ID: 966916725941
Revises: 35c162b5f3d8
Create Date: 2026-02-10 11:12:39.092635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '966916725941'
down_revision: Union[str, Sequence[str], None] = '35c162b5f3d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card_responses', sa.Column('status', sa.Enum('PENDING', 'REVEALED', name='responsestatus'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card_responses', 'status')
    # ### end Alembic commands ###
