"""link journal to user with foreign key

Revision ID: a544a88b6a2f
Revises: cb1c807bd37e
Create Date: 2026-02-08 17:58:13.920628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a544a88b6a2f'
down_revision: Union[str, Sequence[str], None] = 'cb1c807bd37e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('journal')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journal',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('mood_label', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('emotional_needs', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('advice_for_user', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('action_for_user', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('advice_for_partner', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('action_for_partner', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('card_recommendation', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('safety_tier', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('prompt_version', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('model_version', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('parse_success', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('journal_pkey'))
    )
    # ### end Alembic commands ###
