"""Fix card categories and table name

Revision ID: a7cd980a6ab0
Revises: 37e3b353ac83
Create Date: 2026-02-12 09:43:08.909713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a7cd980a6ab0'
down_revision: Union[str, Sequence[str], None] = '37e3b353ac83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. 建立新表 card_decks (ID 是 Integer)
    op.create_table('card_decks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    
    # 2. 強制移除舊表
    op.execute("DROP TABLE IF EXISTS carddeck CASCADE")

    # 3. Analyses 表修改
    op.add_column('analyses', sa.Column('model_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('analyses', sa.Column('parse_success', sa.Boolean(), nullable=False))
    op.drop_index(op.f('ix_analyses_journal_id'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_user_id'), table_name='analyses')
    op.create_unique_constraint(None, 'analyses', ['journal_id'])
    op.drop_constraint(op.f('analyses_user_id_fkey'), 'analyses', type_='foreignkey')
    op.drop_column('analyses', 'user_id')

    # 4. Cards 表修改 (建立新外鍵指到 card_decks)
    op.create_foreign_key(None, 'cards', 'card_decks', ['deck_id'], ['id'])

    # 5. Journals 表修改
    op.add_column('journals', sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('journals', sa.Column('mood', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('journals', sa.Column('tags', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    
    # (上一輪的修正) 加上 server_default 解決舊資料問題
    op.add_column('journals', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.func.now()))
    
    op.add_column('journals', sa.Column('deck_id', sa.Integer(), nullable=True))
    
    # 👇👇👇 [本次修正點] 把 sa.Integer() 改成 sa.UUID()
    op.add_column('journals', sa.Column('card_id', sa.UUID(), nullable=True))
    
    op.create_foreign_key(None, 'journals', 'card_decks', ['deck_id'], ['id'])
    op.create_foreign_key(None, 'journals', 'cards', ['card_id'], ['id'])
    
    op.drop_column('journals', 'model_version')
    op.drop_column('journals', 'action_for_partner')
    op.drop_column('journals', 'advice_for_user')
    op.drop_column('journals', 'action_for_user')
    op.drop_column('journals', 'mood_label')
    op.drop_column('journals', 'emotional_needs')
    op.drop_column('journals', 'advice_for_partner')
    op.drop_column('journals', 'prompt_version')
    op.drop_column('journals', 'safety_tier')
    op.drop_column('journals', 'parse_success')
    op.drop_column('journals', 'card_recommendation')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    raise RuntimeError(
        "Downgrade for revision a7cd980a6ab0 is intentionally unsupported. "
        "This migration performs destructive schema transforms."
    )
