"""add invite_code to user model

Revision ID: cb1c807bd37e
Revises: 4106a6e78900
Create Date: 2026-02-08 16:58:02.355331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cb1c807bd37e'
down_revision: Union[str, Sequence[str], None] = '4106a6e78900'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('invite_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('users', sa.Column('invite_code_created_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_users_invite_code'), 'users', ['invite_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_invite_code'), table_name='users')
    op.drop_column('users', 'invite_code_created_at')
    op.drop_column('users', 'invite_code')
    # ### end Alembic commands ###
