export const HOME_OPTIONAL_DATA_TIMEOUT_MS = 6_000;
export const HOME_OPTIONAL_AUTO_RETRY_DELAY_MS = 2_500;
export const HOME_STATUS_TIMEOUT_MS = 4_000;
export const HOME_TIMELINE_TIMEOUT_MS = 6_000;
