# Settings class and pydantic_settings import live here so app.core.config can be
# imported without loading pydantic (avoids startup hang on some macOS/Python envs).
from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    PROJECT_NAME: str = "Haven"
    API_V1_STR: str = "/api"
    ENV: str = "development"
    LOG_INCLUDE_STACKTRACE: bool = False
    LOG_ROUTE_NORMALIZE_DYNAMIC_SEGMENTS: bool = True
    LOG_SAMPLE_RATE_DEFAULT: float = 1.0
    LOG_SAMPLE_RATE_WS_SEND_FAILURE: float = 1.0
    OTEL_TRACING_ENABLED: bool = False
    TRACE_SPAN_OTEL_MAX_ATTRIBUTES: int = 24
    TRACE_SPAN_OTEL_ATTRIBUTE_ALLOWLIST: str = (
        "context_user_id,context_partner_id,context_session_id,context_mode,"
        "token,user_email,email,route,endpoint,action,event_name,reason,result,"
        "status_code,latency_ms,provider,model,retry,attempt,source"
    )
    METRICS_REQUIRE_AUTH: bool = False
    METRICS_AUTH_TOKEN: str | None = None
    API_IDEMPOTENCY_ENABLED: bool = True
    API_IDEMPOTENCY_TTL_SECONDS: int = 172800
    API_IDEMPOTENCY_MAX_RESPONSE_BYTES: int = 65536
    API_IDEMPOTENCY_MAX_REQUEST_BYTES: int = 131072
    API_IDEMPOTENCY_PURGE_INTERVAL_SECONDS: int = 300
    API_IDEMPOTENCY_PURGE_BATCH_SIZE: int = 500
    ALLOWLIST_ENFORCED: bool = False
    ALLOWLIST_ENFORCED_ENVS: str = "alpha"
    ALLOWED_TEST_EMAILS: str = ""
    ALLOWED_TEST_EMAILS_JSON: str = ""
    POSTHOG_ENABLED: bool = False
    POSTHOG_API_KEY: str | None = None
    POSTHOG_HOST: str = "https://us.i.posthog.com"
    POSTHOG_TIMEOUT_SECONDS: float = 1.0

    DATABASE_URL: str
    DATABASE_READ_REPLICA_URL: str | None = None
    DATABASE_POOL_SIZE: int = 5
    DATABASE_POOL_RECYCLE_SECONDS: int = 1800
    OPENAI_API_KEY: str
    GEMINI_API_KEY: str | None = None
    SECRET_KEY: str
    AI_DYNAMIC_CONTEXT_INJECTION_ENABLED: bool = False
    AI_PERSONA_RUNTIME_GUARDRAIL_ENABLED: bool = True
    AI_ROUTER_PRIMARY_PROVIDER: str = "openai"
    AI_ROUTER_L1_PRIMARY_PROVIDER: str | None = None
    AI_ROUTER_L2_PRIMARY_PROVIDER: str | None = None
    AI_ROUTER_FALLBACK_PROVIDER: str | None = None
    AI_ROUTER_ENABLE_FALLBACK: bool = False
    AI_ROUTER_GEMINI_MODEL: str = "gemini-2.0-flash-lite"
    AI_ROUTER_SHARED_STATE_BACKEND: str = "memory"
    AI_ROUTER_REDIS_URL: str | None = None
    AI_ROUTER_REDIS_KEY_PREFIX: str = "haven:ai-router:"
    AI_ROUTER_FREE_TIER_FIRST_ENABLED: bool = True
    AI_ROUTER_MAX_ATTEMPTS_PER_PROFILE: int = 2
    AI_ROUTER_MAX_TOTAL_ATTEMPTS: int = 4
    AI_ROUTER_MAX_ELAPSED_MS: int = 6500
    AI_ROUTER_BACKOFF_BASE_MS: int = 400
    AI_ROUTER_BACKOFF_MAX_MS: int = 8000
    AI_ROUTER_BACKOFF_JITTER_MODE: str = "full"
    AI_ROUTER_RATE_LIMIT_FAILOVER_THRESHOLD_SECONDS: float = 2.0
    AI_ROUTER_DUPLICATE_POLL_INTERVAL_MS: int = 80
    AI_ROUTER_DUPLICATE_POLL_JITTER_MS_MAX: int = 20
    AI_ROUTER_DUPLICATE_POLL_MAX_CONSECUTIVE_MISS: int = 3
    AI_ROUTER_DUPLICATE_FAST_YIELD_REMAINING_BUDGET_MS: int = 200
    AI_ROUTER_DUPLICATE_EXIT_ACTION: str = "graceful_fallback"
    AI_ROUTER_SCHEMA_FAIL_COOLDOWN_THRESHOLD: int = 3
    AI_ROUTER_SCHEMA_FAIL_WINDOW_SECONDS: int = 60
    AI_ROUTER_SCHEMA_FAIL_COOLDOWN_SECONDS: int = 120
    AI_ROUTER_IDEMPOTENCY_MISMATCH_ACTION: str = "bypass_and_continue"
    AI_ROUTER_RESULT_CACHE_ENABLED: bool = True
    AI_ROUTER_RESULT_CACHE_MODE: str = "success_only"
    AI_ROUTER_RESULT_CACHE_SUCCESS_TTL_JOURNAL_SECONDS: int = 180
    AI_ROUTER_RESULT_CACHE_SUCCESS_TTL_COOLDOWN_SECONDS: int = 45
    AI_ROUTER_RESULT_CACHE_FAILURE_TTL_SECONDS: int = 5
    AI_ROUTER_INFLIGHT_TTL_MS: int = 7000
    AI_ROUTER_DEGRADED_MAX_TOTAL_ATTEMPTS: int = 2
    AI_ROUTER_DEGRADED_DISABLE_SLEEP: bool = True
    AI_ROUTER_DEGRADED_DISABLE_CACHE: bool = True
    AI_ROUTER_DEGRADED_DISABLE_POLL: bool = True
    AI_ROUTER_FORCE_QUALITY_GATE_RED_CLASSES: str = ""
    AI_QUALITY_GATE_SNAPSHOT_FILE: str = ""
    AI_ROUTER_BURN_RATE_ERROR_BUDGET_FRACTION: float = 0.01
    AI_ROUTER_BURN_RATE_FAST_WINDOW_SECONDS: int = 300
    AI_ROUTER_BURN_RATE_SLOW_WINDOW_SECONDS: int = 3600
    AI_ROUTER_BURN_RATE_FAST_THRESHOLD: float = 14.4
    AI_ROUTER_BURN_RATE_SLOW_THRESHOLD: float = 6.0
    AI_ROUTER_BURN_RATE_MIN_ATTEMPTS_FAST: int = 20
    AI_ROUTER_BURN_RATE_MIN_ATTEMPTS_SLOW: int = 100

    ALGORITHM: str = "HS256"
    ACCESS_TOKEN_EXPIRE_MINUTES: int = 60 * 24 * 8
    REFRESH_TOKEN_EXPIRE_DAYS: int = 30
    REFRESH_TOKEN_ROTATION_ENABLED: bool = True
    SQL_ECHO: bool = False
    CORS_ORIGINS: list[str] = ["http://localhost:3000", "http://127.0.0.1:3000"]

    JOURNAL_RATE_LIMIT_COUNT: int = 12
    JOURNAL_RATE_LIMIT_WINDOW_SECONDS: int = 60
    JOURNAL_RATE_LIMIT_IP_COUNT: int = 36
    JOURNAL_RATE_LIMIT_DEVICE_COUNT: int = 24
    JOURNAL_RATE_LIMIT_PARTNER_PAIR_COUNT: int = 24
    CARD_RESPONSE_RATE_LIMIT_COUNT: int = 30
    CARD_RESPONSE_RATE_LIMIT_WINDOW_SECONDS: int = 60
    CARD_RESPONSE_RATE_LIMIT_IP_COUNT: int = 90
    CARD_RESPONSE_RATE_LIMIT_DEVICE_COUNT: int = 60
    CARD_RESPONSE_RATE_LIMIT_PARTNER_PAIR_COUNT: int = 60
    RATE_LIMIT_DEVICE_HEADER: str = "x-device-id"
    PAIRING_ATTEMPT_RATE_LIMIT_COUNT: int = 10
    PAIRING_ATTEMPT_RATE_LIMIT_WINDOW_SECONDS: int = 300
    PAIRING_FAILURE_COOLDOWN_THRESHOLD: int = 5
    PAIRING_FAILURE_COOLDOWN_SECONDS: int = 600
    PAIRING_IP_ATTEMPT_RATE_LIMIT_COUNT: int = 30
    PAIRING_IP_ATTEMPT_RATE_LIMIT_WINDOW_SECONDS: int = 300
    PAIRING_IP_FAILURE_COOLDOWN_THRESHOLD: int = 15
    PAIRING_IP_FAILURE_COOLDOWN_SECONDS: int = 900

    LOGIN_RATE_LIMIT_IP_COUNT: int = 10
    LOGIN_RATE_LIMIT_IP_WINDOW_SECONDS: int = 60
    REGISTRATION_RATE_LIMIT_IP_COUNT: int = 5
    REGISTRATION_RATE_LIMIT_IP_WINDOW_SECONDS: int = 300

    WS_MAX_CONNECTIONS_PER_USER: int = 1
    WS_MAX_CONNECTIONS_GLOBAL: int = 2000
    WS_CONNECTION_RATE_LIMIT_COUNT: int = 60
    WS_CONNECTION_RATE_LIMIT_WINDOW_SECONDS: int = 60
    WS_MESSAGE_RATE_LIMIT_COUNT: int = 120
    WS_MESSAGE_RATE_LIMIT_WINDOW_SECONDS: int = 60
    WS_MESSAGE_BACKOFF_SECONDS: int = 30
    WS_MAX_PAYLOAD_BYTES: int = 4096
    WS_SEND_TIMEOUT_SECONDS: float = 2.0
    WS_SEND_LOCK_WAIT_SECONDS: float = 0.1
    WS_MAX_PENDING_SENDS_PER_USER: int = 8
    WS_MESSAGE_SCOPE_INCLUDE_IP: bool = True
    WS_MESSAGE_SCOPE_INCLUDE_DEVICE: bool = True
    WS_MESSAGE_SCOPE_INCLUDE_PARTNER_PAIR: bool = True
    WS_TYPING_SESSION_CACHE_TTL_SECONDS: float = 8.0
    WS_TYPING_SESSION_CACHE_MAX_ENTRIES: int = 2048
    WEBSOCKET_ENABLED: bool = True

    HEALTH_WS_CONNECTION_ACCEPT_RATE_TARGET: float = 0.995
    HEALTH_WS_MESSAGE_PASS_RATE_TARGET: float = 0.99
    HEALTH_WS_SLI_MIN_CONNECTION_ATTEMPTS: int = 50
    HEALTH_WS_SLI_MIN_MESSAGES: int = 100
    HEALTH_WS_BURN_RATE_FAST_THRESHOLD: float = 14.4
    HEALTH_WS_BURN_RATE_SLOW_THRESHOLD: float = 6.0
    HEALTH_WS_BURN_RATE_MIN_CONNECTION_ATTEMPTS: int = 20
    HEALTH_WS_BURN_RATE_MIN_MESSAGES: int = 40
    HEALTH_PUSH_DELIVERY_RATE_TARGET: float = 0.98
    HEALTH_PUSH_DISPATCH_P95_MS_TARGET: float = 2500.0
    HEALTH_PUSH_DRY_RUN_P95_MS_TARGET: float = 1200.0
    HEALTH_PUSH_SLI_MIN_DISPATCH_ATTEMPTS: int = 5
    HEALTH_PUSH_SLI_MIN_DRY_RUN_SAMPLES: int = 3
    HEALTH_PUSH_STALE_CLEANUP_BACKLOG_MAX: int = 20
    HEALTH_NOTIFICATION_OUTBOX_DEPTH_DEGRADED_THRESHOLD: int = 500
    HEALTH_NOTIFICATION_OUTBOX_OLDEST_PENDING_DEGRADED_SECONDS: int = 1800
    HEALTH_NOTIFICATION_OUTBOX_RETRY_AGE_P95_DEGRADED_SECONDS: int = 2400
    HEALTH_NOTIFICATION_OUTBOX_STALE_PROCESSING_DEGRADED_THRESHOLD: int = 10
    HEALTH_NOTIFICATION_OUTBOX_DISPATCH_LOCK_HEARTBEAT_DEGRADED_SECONDS: int = 180
    HEALTH_NOTIFICATION_OUTBOX_DEAD_LETTER_RATE_DEGRADED_THRESHOLD: float = 0.4
    HEALTH_DYNAMIC_CONTENT_FALLBACK_RATIO_DEGRADED_THRESHOLD: float = 0.65
    HEALTH_DYNAMIC_CONTENT_FALLBACK_MIN_ATTEMPTS: int = 20
    HEALTH_READINESS_CACHE_TTL_SECONDS: float = 5.0

    REDIS_URL: str | None = None
    ASYNC_JOURNAL_ANALYSIS: bool = True
    ABUSE_GUARD_STORE_BACKEND: str = "memory"
    ABUSE_GUARD_REDIS_URL: str | None = None
    ABUSE_GUARD_REDIS_KEY_PREFIX: str = "haven:abuse"

    RESEND_API_KEY: str | None = None
    RESEND_FROM_EMAIL: str = "Haven <noreply@haven.app>"
    EMAIL_NOTIFICATIONS_ENABLED: bool = True
    NOTIFICATION_EMAIL_FALLBACK_DELAY_SECONDS: int = 300
    NOTIFICATION_COOLDOWN_SECONDS: int = 120
    NOTIFICATION_CONSENT_CACHE_SECONDS: int = 30
    NOTIFICATION_OUTBOX_ENABLED: bool = True
    NOTIFICATION_OUTBOX_MAX_ATTEMPTS: int = 3
    NOTIFICATION_OUTBOX_RETRY_BASE_SECONDS: int = 30
    NOTIFICATION_OUTBOX_CLAIM_LIMIT: int = 50
    NOTIFICATION_OUTBOX_ADAPTIVE_BATCHING_ENABLED: bool = True
    NOTIFICATION_OUTBOX_ADAPTIVE_MAX_CLAIM_LIMIT: int = 500
    NOTIFICATION_OUTBOX_ADAPTIVE_AGE_SCALE_THRESHOLD_SECONDS: int = 300
    NOTIFICATION_OUTBOX_ADAPTIVE_AGE_CRITICAL_SECONDS: int = 1200
    NOTIFICATION_OUTBOX_PROCESSING_TIMEOUT_SECONDS: int = 300
    NOTIFICATION_OUTBOX_SENT_RETENTION_DAYS: int = 14
    NOTIFICATION_OUTBOX_DEAD_RETENTION_DAYS: int = 30
    NOTIFICATION_OUTBOX_AUTO_REPLAY_ENABLED: bool = True
    NOTIFICATION_OUTBOX_AUTO_REPLAY_LIMIT: int = 100
    NOTIFICATION_OUTBOX_AUTO_REPLAY_MIN_DEAD_ROWS: int = 50
    NOTIFICATION_OUTBOX_AUTO_REPLAY_MIN_DEAD_LETTER_RATE: float = 0.2
    NOTIFICATION_OUTBOX_BACKLOG_THROTTLE_ENABLED: bool = True
    NOTIFICATION_OUTBOX_BACKLOG_THROTTLE_DEPTH_THRESHOLD: int = 2000
    NOTIFICATION_OUTBOX_BACKLOG_THROTTLE_OLDEST_PENDING_SECONDS_THRESHOLD: int = 1200
    NOTIFICATION_OUTBOX_BACKLOG_THROTTLE_EXEMPT_EVENT_TYPES: str = ""
    NOTIFICATION_OUTBOX_BACKLOG_THROTTLE_EXEMPT_ACTION_TYPES: str = "journal"
    NOTIFICATION_OUTBOX_DISPATCH_LOOP_INTERVAL_SECONDS: int = 15
    NOTIFICATION_OUTBOX_DISPATCH_HEARTBEAT_EVERY: int = 10
    NOTIFICATION_OUTBOX_DISPATCH_LOCK_NAME: str = "notification-outbox-dispatch"
    EVENTS_LOG_RETENTION_DAYS: int = 120
    EVENTS_LOG_PURGE_BATCH_SIZE: int = 2000
    EVENTS_LOG_ROLLUP_ENABLED: bool = True
    EVENTS_LOG_ROLLUP_RETENTION_DAYS: int = 30
    EVENTS_LOG_ROLLUP_BATCH_SIZE: int = 5000
    EVENTS_LOG_JSON_MAX_BYTES: int = 1800
    EVENTS_LOG_TOTAL_JSON_MAX_BYTES: int = 2400
    EVENTS_LOG_INGEST_USER_RATE_LIMIT_COUNT: int = 180
    EVENTS_LOG_INGEST_USER_RATE_LIMIT_WINDOW_SECONDS: int = 60
    EVENTS_LOG_INGEST_STORE_BACKEND: str = "memory"
    EVENTS_LOG_INGEST_REDIS_URL: str | None = None
    EVENTS_LOG_INGEST_REDIS_KEY_PREFIX: str = "haven:events-ingest:"
    RUNTIME_METRICS_SNAPSHOT_PATH: str | None = None

    DYNAMIC_CONTENT_AI_TIMEOUT_SECONDS: float = 12.0
    DYNAMIC_CONTENT_AI_MAX_RETRIES: int = 2
    DYNAMIC_CONTENT_AI_BACKOFF_BASE_SECONDS: float = 0.75
    DYNAMIC_CONTENT_AI_FAILURE_COOLDOWN_SECONDS: float = 300.0
    DYNAMIC_CONTENT_PROVIDER_INIT_RETRY_SECONDS: float = 60.0
    DYNAMIC_CONTENT_SHADOW_MODE: bool = False
    DYNAMIC_CONTENT_COOLDOWN_STORE_RETRY_SECONDS: float = 60.0
    DYNAMIC_CONTENT_DEGRADED_FALLBACK_RATIO_THRESHOLD: float = 0.6
    DYNAMIC_CONTENT_DEGRADED_MIN_ATTEMPTS: int = 10
    DYNAMIC_CONTENT_DEGRADED_DURATION_SECONDS: float = 900.0
    DYNAMIC_CONTENT_DEGRADED_RECOVERY_FALLBACK_RATIO_THRESHOLD: float = 0.35
    DYNAMIC_CONTENT_DEGRADED_RECOVERY_MIN_ATTEMPTS: int = 10
    DYNAMIC_CONTENT_DEGRADED_EXTENSION_SECONDS: float = 300.0

    PUSH_NOTIFICATIONS_ENABLED: bool = False
    WEBPUSH_ENABLED: bool = True
    PUSH_VAPID_PUBLIC_KEY: str | None = None
    PUSH_VAPID_PRIVATE_KEY: str | None = None
    PUSH_VAPID_SUBJECT: str = "mailto:security@haven.app"
    PUSH_JWT_MAX_EXP_SECONDS: int = 86400
    PUSH_DEFAULT_TTL_SECONDS: int = 3600
    PUSH_MAX_SUBSCRIPTIONS_PER_USER: int = 10
    PUSH_DISPATCH_MAX_ACTIVE_SUBSCRIPTIONS: int = 50
    PUSH_DISPATCH_BATCH_SIZE: int = 20
    PUSH_DISPATCH_MAX_CONCURRENCY: int = 5
    PUSH_DISPATCH_RETRY_ATTEMPTS: int = 1
    PUSH_DISPATCH_RETRY_BASE_SECONDS: float = 0.25
    PUSH_DRY_RUN_SAMPLE_SIZE: int = 3
    PUSH_INVALID_RETENTION_DAYS: int = 7
    PUSH_TOMBSTONE_PURGE_DAYS: int = 30

    FEATURE_FLAGS_JSON: str = "{}"
    FEATURE_KILL_SWITCHES_JSON: str = "{}"
    CS_ADMIN_ENABLED: bool = False
    CS_ADMIN_ALLOWED_EMAILS: str = ""
    CS_ADMIN_WRITE_EMAILS: str = ""

    BILLING_STRIPE_SECRET_KEY: str | None = None
    BILLING_STRIPE_PRICE_ID: str | None = None
    BILLING_STRIPE_SUCCESS_URL: str | None = None
    BILLING_STRIPE_CANCEL_URL: str | None = None
    BILLING_STRIPE_PORTAL_RETURN_URL: str | None = None
    BILLING_STRIPE_WEBHOOK_SECRET: str | None = None
    BILLING_STRIPE_WEBHOOK_TOLERANCE_SECONDS: int = 300
    BILLING_STRIPE_WEBHOOK_ASYNC_MODE: bool = False
    BILLING_WEBHOOK_RETRY_MAX_ATTEMPTS: int = 3
    BILLING_WEBHOOK_RETRY_BASE_SECONDS: int = 30

    FIELD_LEVEL_ENCRYPTION_ENABLED: bool = False
    FIELD_LEVEL_ENCRYPTION_KEY: str | None = None
    AUDIT_LOG_RETENTION_DAYS: int = 365
    DATA_EXPORT_EXPIRY_DAYS: int = 7
    STREAK_SUMMARY_CACHE_TTL_SECONDS: int = 300
    DATA_SOFT_DELETE_ENABLED: bool = False
    DATA_SOFT_DELETE_TRASH_RETENTION_DAYS: int = 30
    DATA_SOFT_DELETE_PURGE_RETENTION_DAYS: int = 90
    DATA_SOFT_DELETE_PURGE_EVIDENCE_MAX_AGE_DAYS: int = 14
    WORKER_SINGLETON_LOCK_ENABLED: bool = True
    WORKER_SINGLETON_HEARTBEAT_SECONDS: float = 5.0

    # Cookie 配置（httpOnly 認證）
    ENVIRONMENT: str = "development"  # development, staging, production
    COOKIE_DOMAIN: str | None = None  # 例如：".haven.app" 用於跨子域
    COOKIE_SECURE: bool = False  # 生產環境應設為 True
    # Feature flags (granular)
    TIMELINE_CURSOR_ENABLED: bool = True  # enable cursor-based timeline API by default
    SAFETY_MODE_ENABLED: bool = True
    TIMELINE_CURSOR_MAX_LIMIT: int = 100
    TIMELINE_CURSOR_QUERY_BUDGET: int = 500
    TIMELINE_CURSOR_SIGNING_KEY: str | None = None
    TIMELINE_CURSOR_REQUIRE_SIGNATURE: bool = True
    TIMELINE_CURSOR_ALLOW_DEFAULT_SIGNING_KEY: bool = False

    model_config = SettingsConfigDict(env_file=".env", extra="ignore")


# Global settings instance
settings = Settings()
