"""Shared health/SLO runtime thresholds and WS SLI config."""

from __future__ import annotations

from app.core.config import settings
from app.core.health_ws_sli import WsSliConfig

HEALTH_WS_CONNECTION_ACCEPT_RATE_TARGET = float(settings.HEALTH_WS_CONNECTION_ACCEPT_RATE_TARGET)
HEALTH_WS_MESSAGE_PASS_RATE_TARGET = float(settings.HEALTH_WS_MESSAGE_PASS_RATE_TARGET)
HEALTH_WS_SLI_MIN_CONNECTION_ATTEMPTS = int(settings.HEALTH_WS_SLI_MIN_CONNECTION_ATTEMPTS)
HEALTH_WS_SLI_MIN_MESSAGES = int(settings.HEALTH_WS_SLI_MIN_MESSAGES)
HEALTH_WS_BURN_RATE_WINDOWS_SECONDS = (5 * 60, 60 * 60, 6 * 60 * 60, 24 * 60 * 60)
HEALTH_WS_BURN_RATE_FAST_WINDOW_SECONDS = (5 * 60, 60 * 60)
HEALTH_WS_BURN_RATE_SLOW_WINDOW_SECONDS = (6 * 60 * 60, 24 * 60 * 60)
HEALTH_WS_BURN_RATE_FAST_THRESHOLD = float(settings.HEALTH_WS_BURN_RATE_FAST_THRESHOLD)
HEALTH_WS_BURN_RATE_SLOW_THRESHOLD = float(settings.HEALTH_WS_BURN_RATE_SLOW_THRESHOLD)
HEALTH_WS_BURN_RATE_MIN_CONNECTION_ATTEMPTS = int(
    settings.HEALTH_WS_BURN_RATE_MIN_CONNECTION_ATTEMPTS
)
HEALTH_WS_BURN_RATE_MIN_MESSAGES = int(settings.HEALTH_WS_BURN_RATE_MIN_MESSAGES)
HEALTH_PUSH_DELIVERY_RATE_TARGET = float(settings.HEALTH_PUSH_DELIVERY_RATE_TARGET)
HEALTH_PUSH_DISPATCH_P95_MS_TARGET = float(settings.HEALTH_PUSH_DISPATCH_P95_MS_TARGET)
HEALTH_PUSH_DRY_RUN_P95_MS_TARGET = float(settings.HEALTH_PUSH_DRY_RUN_P95_MS_TARGET)
HEALTH_PUSH_SLI_MIN_DISPATCH_ATTEMPTS = int(settings.HEALTH_PUSH_SLI_MIN_DISPATCH_ATTEMPTS)
HEALTH_PUSH_SLI_MIN_DRY_RUN_SAMPLES = int(settings.HEALTH_PUSH_SLI_MIN_DRY_RUN_SAMPLES)
HEALTH_PUSH_STALE_CLEANUP_BACKLOG_MAX = int(settings.HEALTH_PUSH_STALE_CLEANUP_BACKLOG_MAX)
HEALTH_OUTBOX_DEPTH_DEGRADED_THRESHOLD = int(
    getattr(settings, "HEALTH_NOTIFICATION_OUTBOX_DEPTH_DEGRADED_THRESHOLD", 500)
)
HEALTH_OUTBOX_OLDEST_PENDING_DEGRADED_SECONDS = int(
    getattr(settings, "HEALTH_NOTIFICATION_OUTBOX_OLDEST_PENDING_DEGRADED_SECONDS", 1800)
)
HEALTH_OUTBOX_RETRY_AGE_P95_DEGRADED_SECONDS = int(
    getattr(settings, "HEALTH_NOTIFICATION_OUTBOX_RETRY_AGE_P95_DEGRADED_SECONDS", 2400)
)
HEALTH_OUTBOX_STALE_PROCESSING_DEGRADED_THRESHOLD = int(
    getattr(settings, "HEALTH_NOTIFICATION_OUTBOX_STALE_PROCESSING_DEGRADED_THRESHOLD", 10)
)
HEALTH_OUTBOX_DISPATCH_LOCK_HEARTBEAT_DEGRADED_SECONDS = int(
    getattr(settings, "HEALTH_NOTIFICATION_OUTBOX_DISPATCH_LOCK_HEARTBEAT_DEGRADED_SECONDS", 180)
)
HEALTH_OUTBOX_DEAD_LETTER_DEGRADED_THRESHOLD = float(
    getattr(settings, "HEALTH_NOTIFICATION_OUTBOX_DEAD_LETTER_RATE_DEGRADED_THRESHOLD", 0.4)
)
HEALTH_DYNAMIC_FALLBACK_RATIO_DEGRADED_THRESHOLD = float(
    getattr(settings, "HEALTH_DYNAMIC_CONTENT_FALLBACK_RATIO_DEGRADED_THRESHOLD", 0.65)
)
HEALTH_DYNAMIC_FALLBACK_MIN_ATTEMPTS = int(
    getattr(settings, "HEALTH_DYNAMIC_CONTENT_FALLBACK_MIN_ATTEMPTS", 20)
)
HEALTH_AI_ROUTER_BURN_RATE_FAST_THRESHOLD = float(
    getattr(settings, "AI_ROUTER_BURN_RATE_FAST_THRESHOLD", 14.4)
)
HEALTH_AI_ROUTER_BURN_RATE_SLOW_THRESHOLD = float(
    getattr(settings, "AI_ROUTER_BURN_RATE_SLOW_THRESHOLD", 6.0)
)
HEALTH_AI_ROUTER_BURN_RATE_FAST_WINDOW_SECONDS = int(
    getattr(settings, "AI_ROUTER_BURN_RATE_FAST_WINDOW_SECONDS", 300)
)
HEALTH_AI_ROUTER_BURN_RATE_SLOW_WINDOW_SECONDS = int(
    getattr(settings, "AI_ROUTER_BURN_RATE_SLOW_WINDOW_SECONDS", 3600)
)
HEALTH_AI_ROUTER_BURN_RATE_MIN_ATTEMPTS_FAST = int(
    getattr(settings, "AI_ROUTER_BURN_RATE_MIN_ATTEMPTS_FAST", 20)
)
HEALTH_AI_ROUTER_BURN_RATE_MIN_ATTEMPTS_SLOW = int(
    getattr(settings, "AI_ROUTER_BURN_RATE_MIN_ATTEMPTS_SLOW", 100)
)
HEALTH_AI_ROUTER_BURN_RATE_ERROR_BUDGET_FRACTION = float(
    getattr(settings, "AI_ROUTER_BURN_RATE_ERROR_BUDGET_FRACTION", 0.01)
)
HEALTH_READINESS_CACHE_TTL_SECONDS = max(
    0.0,
    float(getattr(settings, "HEALTH_READINESS_CACHE_TTL_SECONDS", 5.0)),
)

WS_SLI_CONFIG = WsSliConfig(
    connection_accept_rate_target=HEALTH_WS_CONNECTION_ACCEPT_RATE_TARGET,
    message_pass_rate_target=HEALTH_WS_MESSAGE_PASS_RATE_TARGET,
    sli_min_connection_attempts=HEALTH_WS_SLI_MIN_CONNECTION_ATTEMPTS,
    sli_min_messages=HEALTH_WS_SLI_MIN_MESSAGES,
    burn_rate_windows_seconds=HEALTH_WS_BURN_RATE_WINDOWS_SECONDS,
    burn_rate_fast_window_seconds=HEALTH_WS_BURN_RATE_FAST_WINDOW_SECONDS,
    burn_rate_slow_window_seconds=HEALTH_WS_BURN_RATE_SLOW_WINDOW_SECONDS,
    burn_rate_fast_threshold=HEALTH_WS_BURN_RATE_FAST_THRESHOLD,
    burn_rate_slow_threshold=HEALTH_WS_BURN_RATE_SLOW_THRESHOLD,
    burn_rate_min_connection_attempts=HEALTH_WS_BURN_RATE_MIN_CONNECTION_ATTEMPTS,
    burn_rate_min_messages=HEALTH_WS_BURN_RATE_MIN_MESSAGES,
)

__all__ = [
    "HEALTH_AI_ROUTER_BURN_RATE_ERROR_BUDGET_FRACTION",
    "HEALTH_AI_ROUTER_BURN_RATE_FAST_THRESHOLD",
    "HEALTH_AI_ROUTER_BURN_RATE_FAST_WINDOW_SECONDS",
    "HEALTH_AI_ROUTER_BURN_RATE_MIN_ATTEMPTS_FAST",
    "HEALTH_AI_ROUTER_BURN_RATE_MIN_ATTEMPTS_SLOW",
    "HEALTH_AI_ROUTER_BURN_RATE_SLOW_THRESHOLD",
    "HEALTH_AI_ROUTER_BURN_RATE_SLOW_WINDOW_SECONDS",
    "HEALTH_DYNAMIC_FALLBACK_MIN_ATTEMPTS",
    "HEALTH_DYNAMIC_FALLBACK_RATIO_DEGRADED_THRESHOLD",
    "HEALTH_OUTBOX_DEAD_LETTER_DEGRADED_THRESHOLD",
    "HEALTH_OUTBOX_DEPTH_DEGRADED_THRESHOLD",
    "HEALTH_OUTBOX_DISPATCH_LOCK_HEARTBEAT_DEGRADED_SECONDS",
    "HEALTH_OUTBOX_OLDEST_PENDING_DEGRADED_SECONDS",
    "HEALTH_OUTBOX_RETRY_AGE_P95_DEGRADED_SECONDS",
    "HEALTH_OUTBOX_STALE_PROCESSING_DEGRADED_THRESHOLD",
    "HEALTH_PUSH_DELIVERY_RATE_TARGET",
    "HEALTH_PUSH_DISPATCH_P95_MS_TARGET",
    "HEALTH_PUSH_DRY_RUN_P95_MS_TARGET",
    "HEALTH_PUSH_SLI_MIN_DISPATCH_ATTEMPTS",
    "HEALTH_PUSH_SLI_MIN_DRY_RUN_SAMPLES",
    "HEALTH_PUSH_STALE_CLEANUP_BACKLOG_MAX",
    "HEALTH_READINESS_CACHE_TTL_SECONDS",
    "HEALTH_WS_BURN_RATE_FAST_THRESHOLD",
    "HEALTH_WS_BURN_RATE_FAST_WINDOW_SECONDS",
    "HEALTH_WS_BURN_RATE_MIN_CONNECTION_ATTEMPTS",
    "HEALTH_WS_BURN_RATE_MIN_MESSAGES",
    "HEALTH_WS_BURN_RATE_SLOW_THRESHOLD",
    "HEALTH_WS_BURN_RATE_SLOW_WINDOW_SECONDS",
    "HEALTH_WS_BURN_RATE_WINDOWS_SECONDS",
    "HEALTH_WS_CONNECTION_ACCEPT_RATE_TARGET",
    "HEALTH_WS_MESSAGE_PASS_RATE_TARGET",
    "HEALTH_WS_SLI_MIN_CONNECTION_ATTEMPTS",
    "HEALTH_WS_SLI_MIN_MESSAGES",
    "WS_SLI_CONFIG",
]
